wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1639042746
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 3
      - 11
      3:
      - 1
      - 13
      - 16
      4: 3.7.11
      5: 0.12.7
      6: 4.3.2
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
cliprange:
  desc: null
  value: 0.2
cliprange_value:
  desc: null
  value: 0.2
cls_model_name:
  desc: null
  value: mofawzy/arbert-goodreads
forward_batch_size:
  desc: null
  value: 8
gamma:
  desc: null
  value: 1
horizon:
  desc: null
  value: 10000
init_kl_coef:
  desc: null
  value: 0.2
lam:
  desc: null
  value: 0.95
lm_name:
  desc: null
  value: mofawzy/argpt2-goodreads
lr:
  desc: null
  value: 1.41e-05
ppo_epochs:
  desc: null
  value: 4
ref_lm_name:
  desc: null
  value: mofawzy/argpt2-goodreads
seed:
  desc: null
  value: 1
steps:
  desc: null
  value: 51200
target:
  desc: null
  value: 6
tk_name:
  desc: null
  value: gpt2-medium
txt_in_len:
  desc: null
  value: 5
txt_out_len:
  desc: null
  value: 20
vf_coef:
  desc: null
  value: 0.1
